#!/usr/bin/env bash
# Installs and configures HAproxy on lb-01 to load balance web-01 and web-02
# using a round-robin algorithm
# shellcheck disable=SC2154

# Update and install HAproxy
apt-get update -y
apt-get install -y haproxy

# Enable HAproxy to be managed via init script
echo "ENABLED=1" > /etc/default/haproxy

# Configure HAproxy
cat > /etc/haproxy/haproxy.cfg << 'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6968-web-01 18.206.147.173:80 check
    server 6968-web-02 54.91.214.220:80 check
EOF

# Restart HAproxy to apply configuration
service haproxy restart
