#!/usr/bin/env bash
# Installs and configures HAproxy on lb-01 to load balance web-01 and web-02
# using a round-robin algorithm
# shellcheck disable=SC2154

# Update and install HAproxy
apt-get update -y
apt-get install -y haproxy

# Enable HAproxy to be managed via init script
echo "ENABLED=1" > /etc/default/haproxy

#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Make sure that HAproxy can be managed via an init script
sudo apt-get -y update
sudo apt-get -y install haproxy
echo \
"
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend
backend lb-backend
        balance roundrobin
        server 6968-web-01 18.206.147.173:80 check
        server 6968-web-02 54.91.214.220:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
