#!/usr/bin/env bash
# Fix nginx to listen on port 80
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen 8080 default_server/listen 80 default_server/g' /etc/nginx/sites-enabled/default
nginx -t
service nginx restart
