#!/usr/bin/env bash
# Installs and configures Nginx to serve a page with 'Holberton School'

# Install nginx
apt-get update -y
apt-get install -y nginx

# Create the default page with required content
echo 'Holberton School for the win!' > /var/www/html/index.html

# Restart nginx without systemctl
service nginx restart

